package io.github.nidaba.skyforge.reference.provider;

import io.github.nidaba.skyforge.kernel.graph.ArithmeticNode;
import io.github.nidaba.skyforge.kernel.graph.ArithmeticOperator;
import io.github.nidaba.skyforge.kernel.graph.ConstantNode;
import io.github.nidaba.skyforge.kernel.graph.CoordinateAxis;
import io.github.nidaba.skyforge.kernel.graph.CoordinateNode;
import io.github.nidaba.skyforge.kernel.graph.GraphNode;
import io.github.nidaba.skyforge.kernel.graph.GraphValueType;
import io.github.nidaba.skyforge.kernel.graph.IntersectionNode;
import io.github.nidaba.skyforge.kernel.graph.NodeId;
import io.github.nidaba.skyforge.kernel.graph.ProceduralGraph;
import io.github.nidaba.skyforge.kernel.serialization.CanonicalGraphJson;
import io.github.nidaba.skyforge.model.skyisland.SkyIslandVolumeDescriptor;
import io.github.nidaba.skyforge.recipes.skyisland.CompiledSkyIslandVolume;
import io.github.nidaba.skyforge.recipes.skyisland.MorphologyProviderId;
import io.github.nidaba.skyforge.recipes.skyisland.PrimaryMorphologyContribution;
import io.github.nidaba.skyforge.recipes.skyisland.SecondaryMorphologyContribution;
import io.github.nidaba.skyforge.recipes.skyisland.SkyIslandMorphologyProvider;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;

/**
 * Reference-only non-built-in provider used to prove the public morphology SPI.
 *
 * <p>The footprint is a simply connected curved ribbon/boomerang generated by bending the transverse
 * coordinate as a quadratic function of longitudinal position. It intentionally does not delegate
 * to any built-in {@code MorphologyFamily} recipe.
 */
public final class ReferenceCrescentMorphologyProvider implements SkyIslandMorphologyProvider {
    /** Stable proof-provider identity. */
    public static final MorphologyProviderId ID = new MorphologyProviderId("reference", "crescent");
    private static final int RECIPE_VERSION = 10;

    private static final NodeId REMAINING = new NodeId("crescent.profile.remaining");
    private static final NodeId ALONG = new NodeId("crescent.profile.along-normalized");
    private static final NodeId ACROSS = new NodeId("crescent.profile.curved-across-normalized");
    private static final NodeId UPPER_FACTOR = new NodeId("crescent.family.upper-factor");
    private static final NodeId DEPTH_FACTOR = new NodeId("crescent.family.depth-factor");

    @Override
    public MorphologyProviderId id() {
        return ID;
    }

    @Override
    public PrimaryMorphologyContribution compilePrimary(SkyIslandVolumeDescriptor descriptor) {
        if (descriptor.signalAmplitude() != 0.0) {
            throw new IllegalArgumentException("reference crescent primary requires zero detail amplitude");
        }
        if (descriptor.schemaVersion() == SkyIslandVolumeDescriptor.SCHEMA_VERSION_2
                && descriptor.secondaryMorphologyAmplitude() != 0.0) {
            throw new IllegalArgumentException("reference crescent primary requires zero secondary amplitude");
        }

        ProceduralGraph upper = graph(descriptor, Output.UPPER);
        ProceduralGraph underside = graph(descriptor, Output.UNDERSIDE);
        ProceduralGraph density = graph(descriptor, Output.DENSITY);
        CompiledSkyIslandVolume volume = new CompiledSkyIslandVolume(
                descriptor,
                RECIPE_VERSION,
                CanonicalGraphJson.INTERSECTION_SCHEMA_VERSION,
                upper,
                underside,
                density,
                provenance());
        return new PrimaryMorphologyContribution(
                volume,
                REMAINING,
                ALONG,
                ACROSS,
                Optional.empty(),
                UPPER_FACTOR,
                DEPTH_FACTOR);
    }

    @Override
    public Optional<SecondaryMorphologyContribution> compileSecondaryMorphology(
            SkyIslandVolumeDescriptor descriptor, double amplitude) {
        if (!Double.isFinite(amplitude) || amplitude < 0.0 || amplitude > 1.0) {
            throw new IllegalArgumentException("secondary morphology amplitude must be finite and in [0, 1]");
        }
        Builder graph = new Builder(GraphValueType.SCALAR_FIELD_2);
        Profile profile = addProfile(graph, descriptor);
        NodeId one = graph.constant("crescent.secondary.one", 1.0);
        if (amplitude == 0.0) {
            return Optional.of(new SecondaryMorphologyContribution(graph.build(one), 1.0, 1.0));
        }

        NodeId acrossSquared = graph.arithmetic(
                "crescent.secondary.across-squared",
                ArithmeticOperator.MULTIPLY,
                profile.across(),
                profile.across());
        NodeId ridgeDenominator = graph.arithmetic(
                "crescent.secondary.ridge-denominator",
                ArithmeticOperator.ADD,
                one,
                acrossSquared);
        NodeId ridge = graph.arithmetic(
                "crescent.secondary.ridge",
                ArithmeticOperator.DIVIDE,
                one,
                ridgeDenominator);
        NodeId strength = graph.constant("crescent.secondary.strength", 0.22 * amplitude);
        NodeId relief = graph.arithmetic(
                "crescent.secondary.relief",
                ArithmeticOperator.MULTIPLY,
                ridge,
                strength);
        NodeId factor = graph.arithmetic(
                "crescent.secondary.factor",
                ArithmeticOperator.ADD,
                one,
                relief);
        return Optional.of(new SecondaryMorphologyContribution(
                graph.build(factor), 1.0, 1.0 + 0.22 * amplitude));
    }

    private static ProceduralGraph graph(SkyIslandVolumeDescriptor descriptor, Output output) {
        GraphValueType type = output == Output.DENSITY
                ? GraphValueType.SCALAR_FIELD_3
                : GraphValueType.SCALAR_FIELD_2;
        Builder graph = new Builder(type);
        Profile profile = addProfile(graph, descriptor);
        NodeId suspension = graph.constant(
                "crescent.descriptor.suspension-elevation", descriptor.suspensionElevation());
        NodeId upper = addUpper(graph, descriptor, profile, suspension);
        NodeId underside = addUnderside(graph, descriptor, profile, suspension);
        return switch (output) {
            case UPPER -> graph.build(upper);
            case UNDERSIDE -> graph.build(underside);
            case DENSITY -> {
                NodeId y = graph.coordinate("crescent.position.y", CoordinateAxis.Y);
                NodeId upperConstraint = graph.arithmetic(
                        "crescent.density.upper-constraint",
                        ArithmeticOperator.SUBTRACT,
                        upper,
                        y);
                NodeId lowerConstraint = graph.arithmetic(
                        "crescent.density.lower-constraint",
                        ArithmeticOperator.SUBTRACT,
                        y,
                        underside);
                yield graph.build(graph.intersection(
                        "crescent.density.solid-intersection",
                        upperConstraint,
                        lowerConstraint));
            }
        };
    }

    private static Profile addProfile(Builder graph, SkyIslandVolumeDescriptor descriptor) {
        NodeId x = graph.coordinate("crescent.position.x", CoordinateAxis.X);
        NodeId z = graph.coordinate("crescent.position.z", CoordinateAxis.Z);
        NodeId centerX = graph.constant("crescent.descriptor.center-x", descriptor.centerX());
        NodeId centerZ = graph.constant("crescent.descriptor.center-z", descriptor.centerZ());
        NodeId localX = graph.arithmetic(
                "crescent.profile.local-x", ArithmeticOperator.SUBTRACT, x, centerX);
        NodeId localZ = graph.arithmetic(
                "crescent.profile.local-z", ArithmeticOperator.SUBTRACT, z, centerZ);

        double angle = descriptor.ridgeAzimuth();
        NodeId cosine = graph.constant("crescent.profile.cos-angle", Math.cos(angle));
        NodeId sine = graph.constant("crescent.profile.sin-angle", Math.sin(angle));
        NodeId xCos = graph.arithmetic(
                "crescent.profile.x-cos", ArithmeticOperator.MULTIPLY, localX, cosine);
        NodeId zSin = graph.arithmetic(
                "crescent.profile.z-sin", ArithmeticOperator.MULTIPLY, localZ, sine);
        NodeId alongWorld = graph.arithmetic(
                "crescent.profile.along-world", ArithmeticOperator.ADD, xCos, zSin);
        NodeId zCos = graph.arithmetic(
                "crescent.profile.z-cos", ArithmeticOperator.MULTIPLY, localZ, cosine);
        NodeId xSin = graph.arithmetic(
                "crescent.profile.x-sin", ArithmeticOperator.MULTIPLY, localX, sine);
        NodeId acrossWorld = graph.arithmetic(
                "crescent.profile.across-world", ArithmeticOperator.SUBTRACT, zCos, xSin);

        NodeId alongScale = graph.constant(
                "crescent.profile.along-scale", descriptor.nominalRadius() * 1.05);
        NodeId acrossScale = graph.constant(
                "crescent.profile.across-scale", descriptor.nominalRadius() * 0.58);
        NodeId along = graph.arithmetic(
                ALONG.value(), ArithmeticOperator.DIVIDE, alongWorld, alongScale);
        NodeId acrossBase = graph.arithmetic(
                "crescent.profile.across-base-normalized",
                ArithmeticOperator.DIVIDE,
                acrossWorld,
                acrossScale);
        NodeId alongSquared = graph.arithmetic(
                "crescent.profile.along-squared", ArithmeticOperator.MULTIPLY, along, along);
        NodeId bendOffset = graph.constant("crescent.profile.bend-offset", 0.22);
        NodeId bendLocal = graph.arithmetic(
                "crescent.profile.bend-local",
                ArithmeticOperator.SUBTRACT,
                alongSquared,
                bendOffset);
        NodeId bendStrength = graph.constant("crescent.profile.bend-strength", 0.62);
        NodeId bend = graph.arithmetic(
                "crescent.profile.bend",
                ArithmeticOperator.MULTIPLY,
                bendLocal,
                bendStrength);
        NodeId across = graph.arithmetic(
                ACROSS.value(), ArithmeticOperator.SUBTRACT, acrossBase, bend);
        NodeId acrossSquared = graph.arithmetic(
                "crescent.profile.across-squared", ArithmeticOperator.MULTIPLY, across, across);
        NodeId radiusSquared = graph.arithmetic(
                "crescent.profile.radius-squared",
                ArithmeticOperator.ADD,
                alongSquared,
                acrossSquared);
        NodeId one = graph.constant("crescent.profile.one", 1.0);
        NodeId remaining = graph.arithmetic(
                REMAINING.value(), ArithmeticOperator.SUBTRACT, one, radiusSquared);

        NodeId longitudinalDenominator = graph.arithmetic(
                "crescent.family.longitudinal-denominator",
                ArithmeticOperator.ADD,
                one,
                alongSquared);
        NodeId centerBias = graph.arithmetic(
                "crescent.family.center-bias",
                ArithmeticOperator.DIVIDE,
                one,
                longitudinalDenominator);
        NodeId upperBase = graph.constant("crescent.family.upper-base", 0.84);
        NodeId upperStrength = graph.constant("crescent.family.upper-strength", 0.34);
        NodeId upperRelief = graph.arithmetic(
                "crescent.family.upper-relief",
                ArithmeticOperator.MULTIPLY,
                centerBias,
                upperStrength);
        graph.arithmetic(UPPER_FACTOR.value(), ArithmeticOperator.ADD, upperBase, upperRelief);

        NodeId depthBase = graph.constant("crescent.family.depth-base", 0.88);
        NodeId depthStrength = graph.constant("crescent.family.depth-strength", 0.24);
        NodeId depthRelief = graph.arithmetic(
                "crescent.family.depth-relief",
                ArithmeticOperator.MULTIPLY,
                centerBias,
                depthStrength);
        graph.arithmetic(DEPTH_FACTOR.value(), ArithmeticOperator.ADD, depthBase, depthRelief);
        return new Profile(remaining, along, across, radiusSquared, one);
    }

    private static NodeId addUpper(
            Builder graph,
            SkyIslandVolumeDescriptor descriptor,
            Profile profile,
            NodeId suspension) {
        NodeId crown = graph.arithmetic(
                "crescent.upper.crown",
                ArithmeticOperator.MULTIPLY,
                profile.remaining(),
                UPPER_FACTOR);
        NodeId elevation = graph.constant(
                "crescent.descriptor.upper-elevation", descriptor.upperElevation());
        NodeId offset = graph.arithmetic(
                "crescent.upper.offset", ArithmeticOperator.MULTIPLY, elevation, crown);
        return graph.arithmetic(
                "crescent.upper.surface", ArithmeticOperator.ADD, suspension, offset);
    }

    private static NodeId addUnderside(
            Builder graph,
            SkyIslandVolumeDescriptor descriptor,
            Profile profile,
            NodeId suspension) {
        NodeId taper = graph.constant(
                "crescent.descriptor.underside-taper", descriptor.undersideTaper());
        NodeId taperRadius = graph.arithmetic(
                "crescent.underside.taper-radius",
                ArithmeticOperator.MULTIPLY,
                taper,
                profile.radiusSquared());
        NodeId denominator = graph.arithmetic(
                "crescent.underside.taper-denominator",
                ArithmeticOperator.ADD,
                profile.one(),
                taperRadius);
        NodeId taperedRemaining = graph.arithmetic(
                "crescent.underside.tapered-remaining",
                ArithmeticOperator.DIVIDE,
                profile.remaining(),
                denominator);
        NodeId shaped = graph.arithmetic(
                "crescent.underside.shaped-depth",
                ArithmeticOperator.MULTIPLY,
                taperedRemaining,
                DEPTH_FACTOR);
        NodeId depth = graph.constant(
                "crescent.descriptor.underside-depth", descriptor.undersideDepth());
        NodeId offset = graph.arithmetic(
                "crescent.underside.offset", ArithmeticOperator.MULTIPLY, depth, shaped);
        return graph.arithmetic(
                "crescent.underside.surface",
                ArithmeticOperator.SUBTRACT,
                suspension,
                offset);
    }

    private static Map<String, List<NodeId>> provenance() {
        LinkedHashMap<String, List<NodeId>> result = new LinkedHashMap<>();
        result.put("provider:reference:crescent", List.of(REMAINING, ALONG, ACROSS, UPPER_FACTOR, DEPTH_FACTOR));
        return result;
    }

    private enum Output { UPPER, UNDERSIDE, DENSITY }

    private record Profile(
            NodeId remaining,
            NodeId along,
            NodeId across,
            NodeId radiusSquared,
            NodeId one) {}

    private static final class Builder {
        private final GraphValueType type;
        private final List<GraphNode> nodes = new ArrayList<>();

        private Builder(GraphValueType type) {
            this.type = type;
        }

        private NodeId coordinate(String id, CoordinateAxis axis) {
            NodeId result = new NodeId(id);
            nodes.add(new CoordinateNode(result, type, axis));
            return result;
        }

        private NodeId constant(String id, double value) {
            NodeId result = new NodeId(id);
            nodes.add(new ConstantNode(result, type, value));
            return result;
        }

        private NodeId arithmetic(String id, ArithmeticOperator operator, NodeId left, NodeId right) {
            NodeId result = new NodeId(id);
            nodes.add(new ArithmeticNode(result, type, operator, left, right));
            return result;
        }

        private NodeId intersection(String id, NodeId left, NodeId right) {
            NodeId result = new NodeId(id);
            nodes.add(new IntersectionNode(result, left, right));
            return result;
        }

        private ProceduralGraph build(NodeId output) {
            return new ProceduralGraph(nodes, output);
        }
    }
}
