package io.github.nidaba.skyforge.neoforge1211;

/** Stable failure vocabulary for bounded compiler-program integration fixtures. */
enum SkyforgeCompilerIntegrationFailure {
    FAIL_DEPENDENCY_RESOLUTION,
    FAIL_TARGET_LOWERING,
    FAIL_BOOT,
    FAIL_RUNTIME_EXIT,
    FAIL_PLACEMENT,
    FAIL_BLOCK_ENTITY_INIT,
    FAIL_GLUE_REGISTRATION,
    FAIL_ASSEMBLY,
    FAIL_CHILD_ASSEMBLY,
    FAIL_KINETIC_REBUILD,
    FAIL_NETWORK,
    FAIL_CLIENT_INTERACTION,
    FAIL_PASSENGER_TRACKING,
    FAIL_PHYSICS,
    FAIL_PERSISTENCE,
    TIMEOUT_SERVER_BOOT,
    TIMEOUT_GLUE_REGISTRATION,
    TIMEOUT_ASSEMBLY_REGISTRATION,
    TIMEOUT_PHYSICS_INITIALIZATION,
    TIMEOUT_PHYSICS_PROGRESSION,
    TIMEOUT_KINETIC_BUILD,
    TIMEOUT_KINETIC_DISCONNECT,
    TIMEOUT_KINETIC_REBUILD,
    TIMEOUT_FIXTURE_TERMINAL_STATE
}
