modLoader="javafml"
loaderVersion="[1,)"
license="All Rights Reserved"

[[mods]]
modId="skyforge"
version="0.1.0"
displayName="Skyforge"
description='''Backend-neutral floating-island realization for Minecraft through NeoForge.'''

[[dependencies.skyforge]]
modId="neoforge"
type="required"
versionRange="[21.1.249,)"
ordering="NONE"
side="BOTH"

[[dependencies.skyforge]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"
