"use strict";
const assert=require("node:assert/strict");
const {compare}=require("../orchestrator/studio/regional-comparison.js");
const row=(association,metal,volumeId,eligible,mean,peak)=>({association,metal,volumeId,eligible,mean,peak,meanText:String(mean),peakText:String(peak)});
const inventory=entries=>({entries,associationCount:new Set(entries.map(x=>x.association)).size});
const left=inventory([row("a","IRON","v1",true,4,8),row("a","COPPER","v1",false,0,0),row("b","IRON","v2",true,2,3)]);
const right=inventory([row("a","IRON","v9",true,5,9),row("a","COPPER","v9",true,1,2),row("c","IRON","v3",true,7,8)]);
const result=compare(left,right,[{association:"a",metal:"IRON",rankText:"0"}],[{association:"a",metal:"IRON",rankText:"1"}]);
assert.deepEqual(result.rows.map(x=>[x.association,x.metal,x.status]),[["a","IRON","changed"],["a","COPPER","changed"],["b","IRON","removed"],["c","IRON","added"]]);
assert.equal(result.rows[0].meanDelta,1);
assert.equal(result.rows[0].rankDelta,1);
assert.equal(result.counts.find(x=>x.metal==="IRON").delta,0);
assert.equal(result.counts.find(x=>x.metal==="COPPER").delta,1);
assert.equal(compare(left,right,null,null).rows[0].rankDelta,null);
console.log("Studio regional inventory comparison contract passed.");
